name: Validate Branch Name

on:
  pull_request:
    branches:
      - main

jobs:
  validate_branch_name:
    runs-on: 'ubuntu-latest'
    steps:

      - name: Validate branch name and PR creator from VN
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          PR_CREATOR="${GITHUB_ACTOR}"

          if [[ "$PR_CREATOR" =~ -zigexn$ ]] && ([[ "$BRANCH_NAME" =~ ^(feature|bug|hotfix|revert|business-rollback)/RSP-LSDIVISON-[0-9]+$ ]] || [[ "$BRANCH_NAME" =~ ^vn_contribution ]]); then
            echo "✅ Validation passed: Branch name and PR creator are valid"
          else
            echo "❌ Validation failed"
            exit 1
          fi
